# Generated by Django 4.2.21 on 2025-05-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_category_remove_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
